SSV Andromeda WIP
Helixis/Shiptest pull request #9
Opened 2023-07-20 20:20 UTC by NervalARS

Añade la SSV Andromeda

## About The Pull Request

Añade una nueva clase de nave de gran tamaño llamada Andromeda-class

## Why It's Good For The Game

Añade mas variedad, concretamente una nueva nave, además de un poco mas de lore. Lo estoy haciendo por puro hobbie y para que la gente disfrute de mi trabajo.

## Changelog

:cl:
add: Nave clase Andromeda
/:cl:

2023-07-25 02:49 UTC, SagaStars requested changes
Haz la mierda de disc.

2023-08-01 19:38 UTC, SagaStars approved these changes

2023-08-03 17:47 UTC, Tilk1 commented
La foto esta actualizada? Es esta la nave mas rapida del servidor? Considerando la cantidad de motores creo que podria serlo. En caso de serlo se me hace un poco extraño y forzado

2023-08-04 00:32 UTC, kokolo21 commented
Pasa todos los tests excepto el de areas pero no es importante para esto. 👍

2023-08-04 00:41 UTC, merged